name: Greetings

on: [pull_request, issues,push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank You for contributing to this repo'
        pr-message: 'Thank You for contributing to this repo'
        push-message: 'Thank You for contributing to this repo'
